import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Navbar from "@/components/navbar";


const helvetica_init = localFont({
  src: './fonts/Helvetica.ttf',
  weight: '400',
  variable: '--font-helvetica',

})
// Helvetica
const inter_init = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Food Delivery Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-black" lang="en">
      <body className={`${inter_init.variable} ${helvetica_init.variable}` } >

        <Navbar />
        {children}
      </body>
    </html>
  );
}
